# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_collect', models.BooleanField(verbose_name='\u662f\u5426\u6536\u85cf')),
            ],
            options={
                'verbose_name': '\u6536\u85cf',
                'verbose_name_plural': '\u6536\u85cf',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=b'2017-10-19 06:06:35', verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='collect',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_article', to='article.article', verbose_name='\u6536\u85cf\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u7528\u6237'),
        ),
    ]
