# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171019_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='has_collect',
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=b'2017-10-19 07:07:21', verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
