# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171020_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=b'2017-10-23 05:05:45', verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
