# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-10 10:50
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('body', DjangoUeditor.models.UEditorField(default=b'', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('click', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe5\x87\xbb\xe6\x95\xb0')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 1, 10, 10, 50, 46, 53000, tzinfo=utc), verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 1, 10, 10, 50, 46, 52000, tzinfo=utc), verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tags', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
