# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-08 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2018, 1, 8, 23, 53, 11, 4000), verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
