# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 14:47
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180108_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2018, 1, 9, 22, 47, 54, 725000), verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=DjangoUeditor.models.UEditorField(default=b'', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
