# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180111_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[(b'yc', b'\xe5\x8e\x9f\xe5\x88\x9b'), (b'zz', b'\xe8\xbd\xac\xe8\xbd\xbd')], default=b'yc', max_length=4),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='blogs.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb'),
        ),
    ]
